name: pamsimas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  cloud_firestore: ^4.2.0
  google_sign_in: ^5.4.2
  lottie: 2.0.0
  introduction_screen: 3.1.1
  flutter_svg: 1.1.6
  fluttertoast: 8.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/images/
  fonts: 
    - family: Mukta
      fonts: 
        - asset: assets/fonts/Mukta/Mukta-Regular.ttf
  uses-material-design: true

